### ISSUE TITLE
Allow "pull" of repository, if the repository already exists at the target path

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/steps-git-clone#14]
Should check the remote URL, to prevent accidental overwrite of the target, but if the remote matches the one defined as the input of the step then it could just to a git fetch/pull, instead of a full git clone.

**Comment by viktorbenei** [comment]
This would allow source code caching, when used with the Build Cache (https://github.com/bitrise-io/bitrise-contrib/issues/15#issuecomment-226365446)

**Comment by birmacher** [comment]
@viktorbenei Should we close the ticket It was solved in #20. Or is there anything else?

**Comment by viktorbenei** [comment]
I guess we should ;)
