### ISSUE TITLE
Feature request: add commit count as output variable from this step

### ISSUE THREAD

**Issue by takn** [bitrise-io/steps-git-clone#23]
In our project we would like to use the commit count instead of the build number for versioning. 
It would be useful for this step to output a variable with the commit count.
`
GIT_CLONE_COMMIT_COUNT = git rev-list --count HEAD`

**Comment by viktorbenei** [comment]
Of course, if anyone would have the time to implement it before we could, just leave a comment here that you're working on it ;)
