### ISSUE TITLE
Option to disable git submodule update

### ISSUE THREAD

**Issue by leesah** [bitrise-io/steps-git-clone#32]
I'm using a private project as a submodule, which is not accessible to others, including bitrise.io. But this submodule is only for deployment use and unit test doesn't rely on it. So as long as git-clone step skips it my workflow can continue.

**Comment by godrei** [comment]
Hi @leesah , thanks for the feature request!
I scheduled to solve this!

**Comment by viktorbenei** [comment]
Just a question @leesah - if that repo should not be part of the build, wouldn't it better to not have it as a submodule in your main repo?

I mean, if that's a submodule then a git clone step **should** fail if can't access it.

IMO the better solution would be to not to have that in the repo as a submodule if that's not required for your project; just have it as a separate repo and clone it where you need it.

Is there any reason why you don't want to do this, why you **need** it as a submodule?

I'm just curious, and try to understand whether this functionality should be built into this step or not.

**Comment by leesah** [comment]
Hi @viktorbenei , the submodule is my android keystore which I host as a private git repo in Gitlab.com. I know `bitrise.io` provides a secret storage option for this, but I just don't wanna get tied to it now. When I run unit tests & instrumental tests in bitrise.io, this submodule is not needed as I am not assigning a signing config in debug build config. It's only used when I run my `release` job in Gitlab-CI which will build a signed apk and publish to Google Play. And Gitlab-CI jobs are run with my own permissions, so there won't be a problem updating the submodule even it's private.

**Comment by leesah** [comment]
BTW, I am using a submodule instead of a separate git clone command because it's easier to have a fixed relative path to the keystore file in `build.gradle`.

**Comment by viktorbenei** [comment]
Hi,

Sorry for the long delay. We're still discussing whether we should add this as a simple "checkout submoduled?" option, or do it another way. We'll try to decide what the best solution would be on Monday, and implement it ASAP.

Just a quick question, as you have an interesting setup (multi CI systems): what's the reason you use GitLab for release? And do you run those releases on a local agent, running on your Mac/PC?

**Comment by viktorbenei** [comment]
Another question, if you don't mind: why do you store the keystore in git, and why not somewhere else, e.g. in the Secrets storage provided by Bitrise.io (but other services provide similar features as well - although I'm not sure about GitLab specifically)? Doesn't GitLab have a feature for this?

**Comment by leesah** [comment]
No, GitLab doesn't provide such a storage. That's why I came up with this idea to have a private repo for it. As for the reason of having multiple CI setups, maybe you are right, I don't know..., I just wanted to try both, I guess. -_- The project itself is for fun, anyways.

**Comment by viktorbenei** [comment]
> The project itself is for fun, anyways.

Sure, fun is the best kind of project! ;)
I'm just not sure whether we should add this as an option to this step directly, or maybe there's a better solution overall.

But rest assured, it's scheduled for a discussion tomorrow, and we'll find a solution ;)

**Comment by bloodrabbit** [comment]
Thanks for the feedback @leesah!
We see how this can be useful for some teams, but as this is not a standard use case that comes up, we've decided to add it to our backlog for later review.

**Comment by leesah** [comment]
@bloodrabbit Sure. I love your work with the bitrise projects BTW.

**Comment by viktorbenei** [comment]
Thanks @leesah and we'll definitely come back to this task, we just have so many things scheduled that we had to push it back a bit. Sorry for the inconvenience.

**Comment by viktorbenei** [comment]
@leesah a new option is now available to not to init submodules at all: https://github.com/bitrise-io/steps-git-clone/issues/35

It's an "all or nothing" solution, either init all submodules or non at all, not sure if that helps in your specific case, but wanted to mention in case it does :)

**Comment by leesah** [comment]
Thanks! It's nice of you to notify me.
