### ISSUE TITLE
No way to disable submodule clone?

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-io/steps-git-clone#35]
I have a large submodule that's not needed for certain builds.

> git "submodule" "update" "--init" "--recursive"

The submodule update command is always run. It'd be nice to have a config option to disable submodule updates.

**Comment by viktorbenei** [comment]
Thanks for the feature request @bootstraponline - added this to our backlog, we'll try to add the option ASAP ;)

**Comment by godrei** [comment]
Hi @bootstraponline ,
we released a new version ([3.5.0](https://github.com/bitrise-io/steps-git-clone/releases/tag/3.5.0)) of the step, this version got a new input: `update_submodules`, set this input's value to `no`, to disable submodule update.
