### ISSUE TITLE
Smart git retry

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-io/steps-git-clone#38]
The bitrise git clone step retries on any failure and uses a low try count of two. On chromium, they're defaulting to 5 retries. A white list of failures known to be resolved on retry is used to prevent retrying errors that will always occur.

Ideally, this best practice would be applied to all steps (defining a list of known failures & retrying 5x). This is faster than blindly retrying all failures (as we skip non-transient failures) and also more reliable (we can retry more times).

```python
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

DEFAULT_DELAY_SECS = 3.0
DEFAULT_RETRY_COUNT = 5

def shouldRetry(self, stderr):
  m = GIT_TRANSIENT_ERRORS_RE.search(stderr)
```

```python
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Retry a git operation if git returns a error response with any of these
# messages. It's all observed 'bad' GoB responses so far.
#
# This list is inspired/derived from the one in ChromiumOS's Chromite:
# <CHROMITE>/lib/git.py::GIT_TRANSIENT_ERRORS
#
# It was last imported from '7add3ac29564d98ac35ce426bc295e743e7c0c02'.
GIT_TRANSIENT_ERRORS = (
    # crbug.com/285832
    r'!.*\[remote rejected\].*\(error in hook\)',
    # crbug.com/289932
    r'!.*\[remote rejected\].*\(failed to lock\)',
    # crbug.com/307156
    r'!.*\[remote rejected\].*\(error in Gerrit backend\)',
    # crbug.com/285832
    r'remote error: Internal Server Error',
    # crbug.com/294449
    r'fatal: Couldn\'t find remote ref ',
    # crbug.com/220543
    r'git fetch_pack: expected ACK/NAK, got',
    # crbug.com/189455
    r'protocol error: bad pack header',
    # crbug.com/202807
    r'The remote end hung up unexpectedly',
    # crbug.com/298189
    r'TLS packet with unexpected length was received',
    # crbug.com/187444
    r'RPC failed; result=\d+, HTTP code = \d+',
    # crbug.com/388876
    r'Connection timed out',
    # crbug.com/430343
    # TODO(dnj): Resync with Chromite.
    r'The requested URL returned error: 5\d+',
    r'Connection reset by peer',
    r'Unable to look up',
    r'Couldn\'t resolve host',

```

- https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/master/git_retry.py
- https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/master/git_common.py

**Comment by viktorbenei** [comment]
Great idea @bootstraponline !

Added the `help wanted` tag, as we probably won't have time for this in the near future but PRs are of course welcome.

The reason why this got a lower priority is that this Git Clone step already has a base "selective retry". This step performs the clone in multiple steps, usually something like 

```
=> git "init"
=> git "remote" "add" "origin" "https://github.com/bitrise-samples/sample-apps-android-sdk22.git"
=> git "fetch"
=> git "checkout" "master"
=> git "submodule" "update" "--init" "--recursive"
```

and the step will only retry the network related commands (e.g. `git fetch`) and won't retry the non network related ones (e.g. `git init` or `git remote add`).

This definitely could be improved, but for now we can't bump its priority higher, unfortunately. But of course PRs are always welcome ;)

**Comment by ninjaprox** [comment]
@viktorbenei: I'd like to add this improvement to the step. To facilitate this, I'm thinking of adding a method to `github.com/bitrise-io/go-utils/retry` package to retry on certain condition, then make appropriate changes according to the suggestion above. What do you think?

**Comment by bootstraponline** [comment]
https://github.com/bitrise-io/steps-gradle-runner/blob/ba03ffbd5182bb0d57b8b66cacf743e1bb3ef47f/main.go#L28 is a good example of how to retry based on a white list.

**Comment by bootstraponline** [comment]
After reviewing many build logs via an automated tool, the existing retry seems to be working fine. As a result, I'm closing the feature request.
