### ISSUE TITLE
Output variables being wrapped in quotes

### ISSUE THREAD

**Issue by realdealbiehl** [bitrise-io/steps-git-clone#60]
It looks like all output variables are being wrapped in quotes and this is causing other steps to have issues. For example: $GIT_CLONE_COMMIT_HASH

used to be: 450974c4f3badf9613503edc092eaaf51efc45b6
latest build: "450974c4f3badf9613503edc092eaaf51efc45b6"

**Comment by viktorbenei** [comment]
Thanks for reporting @realdealbiehl  we'll fix this asap! 😊

**Comment by kdobmayer** [comment]
Hi @realdealbiehl , we fixed the issue in release [4.0.4](https://github.com/bitrise-io/steps-git-clone/releases/tag/4.0.4).

**Comment by realdealbiehl** [comment]
Thank you @kdobmayer I will give it a test
