### ISSUE TITLE
Support sparse checkouts

### ISSUE THREAD

**Issue by amayers** [bitrise-io/steps-git-clone#66]
It would be nice if you could support sparse checkouts so we could significantly speed up a clone (would save ~30 second per build, 50% of the cone time) for our repo, as we have multiple projects in the repo, but the CI doesn't need to build but ~50% at per build.

**Comment by viktorbenei** [comment]
Hi @amayers ,

Could you please clarify what you mean by "sparse checkout"?

**Comment by viktorbenei** [comment]
Closing this issue due to the lack of information - feel free to share more details and we'll reopen it! :)
