### ISSUE TITLE
Disable git LFS

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-io/steps-git-clone#75]
Using a mono repo with a 15MB file, we're exceeding 70GB of bandwith per month. Most of these clones have no need for the LFS files. It'd be great if we had an option in git clone to ignore the LFS files and not download them from GitHub. This is similar to the skip submodules feature.

**Comment by bootstraponline** [comment]
Workaround:

```bash
#!/usr/bin/env bash
set -e

echo "" > `which git-lfs`
echo "Git LFS disabled"
```

**Comment by viktorbenei** [comment]
Thanks for the feature request @bootstraponline !

Do you have a suggestion, how it should be disabled in this step? E.g. a git flag or similar?

**Comment by bootstraponline** [comment]
Maybe lfs.fetchexclue = "*" or the -X flag.


https://github.com/git-lfs/git-lfs/issues/227

**Comment by bootstraponline** [comment]
1) `-X` only works with selected `git lfs` commands, not regular git. It's not supported on checkout.

2) creating a `.lfsconfig` in the source dir makes the working directory dirty.
```
cat << 'EOF' >> ./.lfsconfig
[lfs]
	fetchexclude = *
EOF
```

3) Zeroing out the lfs binary seems to be the best solution.
`echo "" > `which git-lfs``

What do you think about a PR that adds a checkbox to the git clone step that removes the lfs binary when enabled?

**Comment by viktorbenei** [comment]
Disabling / removing the binary seems to be a bit too dramatic solution to be built into the step, steps should not affect the system as much as possible, as users might run them on their own Mac/Linux using the CLI.

**Comment by bootstraponline** [comment]
If we go with the `.lfsconfig` file approach, then I think that'll cause conflicts if someone has that file already checked into the repo.

I'm not sure there's an elegant non-destructive solution. I agree if people are running workflows locally, deleting the binary is not a great solution.

**Comment by bootstraponline** [comment]
Maybe `git lfs uninstall` after git clone would work.

**Comment by viktorbenei** [comment]
Sounds better, but I'm still not sure if this should be part of this, the Git Clone step. Git LFS is not installed or configured by this step, so far there's no functionality in this step related to LFS.

**Comment by bootstraponline** [comment]
I tested and the filtering stage where LFS downloads happen is skipped.

```bash
git lfs uninstall ;\
git "init" ;\
git "remote" "add" "origin" "git@github.com:example/repo.git";\
git "fetch";\
git "checkout" "master"
git "merge" "origin/master"
git "submodule" "update" "--init" "--recursive"
```

```
Checking out files: 100% (6239/6239), done.
Branch 'master' set up to track remote branch 'master' from 'origin' by rebasing.
```

without uninstall:

```

Checking out files: 100% (6239/6239), done.
Filtering content: 100% (2/2), 23.62 MiB | 5.07 MiB/s, done.
Branch 'master' set up to track remote branch 'master' from 'origin' by rebasing.
```

What do you think about a PR for that? ^

**Comment by bootstraponline** [comment]
> Git LFS is not installed or configured by this step, so far there's no functionality in this step related to LFS.

Git clone is how LFS is being run though. With the current step, there's no way to clone without LFS activating.

**Comment by viktorbenei** [comment]
Adding a Script before the Git Clone step with `git lfs uninstall` would be my current recommendation.

**Comment by viktorbenei** [comment]
I'll bring this up for a discussion with the team, but for me it seems strange to have an LFS uninstall option/functionality in this step. Still a bit too destructive for local runs..

**Comment by bootstraponline** [comment]
It sounds like a LFS remove step that runs only on bitrise (and no-ops for local runs) is the best solution. Thanks for your feedback!

**Comment by viktorbenei** [comment]
In any case I created an internal task for this, we'll do some research to see if there's any other option to disable LFS, either just temporarily while the step runs, or just for the current project instead of for the whole machine - preferably both at the same time, only for the repo and only for the duration of the step :)

**Comment by bootstraponline** [comment]
It seems like you could check the output of `lfs uninstall`, if it did anything then run `lfs install` at the end of the step.

**Comment by viktorbenei** [comment]
Indeed, something like that might work - we'll see if that's the best option ;)

**Comment by bootstraponline** [comment]
FYI git lfs uninstall doesn't seem to work after all:
https://www.bitrise.io/build/f485c04ca85bcc7e

probably I'll do something like:

```
LFS=`which git-lfs`
mv $LFS $LFS.bak
echo "" > $LFS
mv $LFS.bak $LFS
```

Ping me if you find a better way. 😄

**Comment by viktorbenei** [comment]
Ohh my.. I definitely will 😂

**Comment by bootstraponline** [comment]
One of the LFS core devs shared this:

> git config --global lfs.fetchexclude '*'`

That should disable LFS fetching. https://github.com/git-lfs/git-lfs/issues/2919#issuecomment-374393246

**Comment by viktorbenei** [comment]
Awesome, thanks for the info @bootstraponline !

Did you verify that it works if you run it as a Script step before the Git Clone one?

**Comment by bootstraponline** [comment]
> Did you verify that it works if you run it as a Script step before the Git Clone one?

yes

**Comment by bootstraponline** [comment]
I made a step and it's working: https://github.com/instructure/steps-disable-git-lfs

**Comment by viktorbenei** [comment]
Looks great, thanks for sharing @bootstraponline ! ;)
