### ISSUE TITLE
Permission denied (publickey,password) when use ssh TFS and Bitrise.

### ISSUE THREAD

**Issue by joaomoraiseu** [bitrise-io/steps-git-clone#81]
I have some troubles with Bitrise and Microsoft Team Foundation Server.

Switching to workflow: validation_workflow_with_ssh

+------------------------------------------------------------------------------+
| (0) Activate App SSH key                                                     |
+------------------------------------------------------------------------------+
| id: activate-ssh-key                                                         |
| version: 3.1.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2018-05-16T20:08:55Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[20:08:55] sudo "apt-get" "update"                      
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:3 https://packages.cloud.google.com/apt cloud-sdk-xenial InRelease [6,372 B]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Hit:5 https://dl.yarnpkg.com/debian stable InRelease
Get:6 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:7 https://download.docker.com/linux/ubuntu xenial InRelease [65.8 kB]
Get:8 https://packages.cloud.google.com/apt cloud-sdk-xenial/main amd64 Packages [35.6 kB]
Get:9 https://packages.cloud.google.com/apt cloud-sdk-xenial/main i386 Packages [35.4 kB]
Get:10 https://deb.nodesource.com/node_8.x xenial InRelease [4,643 B]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [80.4 kB]
Hit:12 https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease
Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [255 kB]
Get:14 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [626 kB]
Get:15 https://deb.nodesource.com/node_8.x xenial/main amd64 Packages [1,009 B]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1,002 kB]
Get:17 http://security.ubuntu.com/ubuntu xenial-security/main i386 Packages [557 kB]
Get:18 https://deb.nodesource.com/node_8.x xenial/main i386 Packages [999 B]
Get:19 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [439 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [922 kB]
Get:21 http://security.ubuntu.com/ubuntu xenial-security/universe i386 Packages [378 kB]
Get:22 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [808 kB]
Get:23 http://archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [742 kB]
Fetched 6,282 kB in 2s (2,674 kB/s)

INFO[20:09:02] Start installing (expect) with apt-get       
INFO[20:09:02]  * [OK] Step dependency (expect) installed, available. 
INFO[20:09:02] Start installing (git) with apt-get          
INFO[20:09:02]  * [OK] Step dependency (git) installed, available. 

# Configuration

* Path to save the RSA SSH private key: */root/.ssh/steplib_ssh_step_id_rsa*
* Should remove other identities from the ssh-agent? *true*
-> $ mkdir -p /root/.ssh
-> $ chmod 0600 /root/.ssh/steplib_ssh_step_id_rsa
 (i) ssh_agent_check_result: 2
 (i) ssh-agent not started
 (i) starting a new ssh-agent and exporting connection information with envman
Could not open a connection to your authentication agent.
Agent pid 579
 (i) Expose SSH_AUTH_SOCK for the new ssh-agent, with envman
spawn ssh-add /root/.ssh/steplib_ssh_step_id_rsa
Identity added: /root/.ssh/steplib_ssh_step_id_rsa (/root/.ssh/steplib_ssh_step_id_rsa)

# Success

The SSH key was saved to */root/.ssh/steplib_ssh_step_id_rsa*
and was successfully added to ssh-agent.
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | Activate App SSH key                                          | 9.46 sec |
+---+---------------------------------------------------------------+----------+

                                          ▼

+------------------------------------------------------------------------------+
| (1) Git Clone Repository                                                     |
+------------------------------------------------------------------------------+
| id: git-clone                                                                |
| version: 3.4.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2018-05-16T20:09:03Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[20:09:03] Start installing (golang) with apt-get       
INFO[20:09:03]  * [OK] Step dependency (go) installed, available. 

Git Clone Configs:
- CloneIntoDir: /bitrise/src
- RepositoryURL: ssh://tfs.######.com.br:22/tfs/Projetos/#####/_git/########"
Git Checkout Configs:
- Commit: 
- Tag: 
- Branch: master
- CloneDepth: 
Git Pull Request Configs:
- PullRequestURI: 
- PullRequestID: 
- BranchDest: 
- PullRequestMergeBranch: 
- ResetRepository: No
Bitrise Build Configs:
- BuildURL: 
- BuildAPIToken: 

Git clone repository
=> git "init"
=> git "remote" "add" "origin" "ssh://tfs.######.com.br:22/tfs/Projetos/#####/_git/########"
=> git "fetch"
0 attempt failed:
Warning: Permanently added 'tfs.iterative.com.br,201.16.245.209' (ECDSA) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Retrying...
=> git "fetch"
1 attempt failed:
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Retrying...
=> git "fetch"
2 attempt failed:
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Failed, error: Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Git Clone Repository (exit code: 1)                           | 13 sec   |
+---+---------------------------------------------------------------+----------+
| Update available: 3.4.3 -> 4.0.11                                            |
| Issue tracker: https://github.com/bitrise-io/steps-git-clone/issues          |
| Source: https://github.com/bitrise-io/steps-git-clone                        |
+---+---------------------------------------------------------------+----------+

                                          ▼

INFO[20:09:15] Step uses latest version -- Updating StepLib ... 
INFO[20:09:15] Update StepLib (https://github.com/bitrise-io/bitrise-steplib.git)... 
WARN[20:09:19] A previous step failed, and this step (Running project scanner) was not marked as IsAlwaysRun, skipped 
+------------------------------------------------------------------------------+
| (2) Running project scanner                                                  |
+------------------------------------------------------------------------------+
| id: project-scanner                                                          |
| version: 1.6.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2018-05-16T20:09:19Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
|                                                                              |
+---+---------------------------------------------------------------+----------+
| - | Running project scanner                                       | 4.52 sec |
+---+---------------------------------------------------------------+----------+

+------------------------------------------------------------------------------+
|                               bitrise summary                                |
+---+---------------------------------------------------------------+----------+
|   | title                                                         | time (s) |
+---+---------------------------------------------------------------+----------+
| ✓ | Activate App SSH key                                          | 9.46 sec |
+---+---------------------------------------------------------------+----------+
| x | Git Clone Repository (exit code: 1)                           | 13 sec   |
+---+---------------------------------------------------------------+----------+
| Update available: 3.4.3 -> 4.0.11                                            |
| Issue tracker: https://github.com/bitrise-io/steps-git-clone/issues          |
| Source: https://github.com/bitrise-io/steps-git-clone                        |
+---+---------------------------------------------------------------+----------+
| - | Running project scanner                                       | 4.52 sec |
+---+---------------------------------------------------------------+----------+
| Total runtime: 27 sec                                                        |
+------------------------------------------------------------------------------+

Submitting anonymized usage informations...
For more information visit:
https://github.com/bitrise-core/bitrise-plugins-analytics/blob/master/README.md

Im using a personal SSH Key in Integration, but the git clone proccess fails. Via Http protocol the Integration works fine.

What is this issue?

Thanks

**Comment by godrei** [comment]
Hi @joaomoraiseu ,
do you use your own ssh key or the one generated by bitrise at your project registration? Did you register the ssh key for your TFS  project?

**Comment by godrei** [comment]
Closing as we did not receive a reply - @joaomoraiseu please let us know if we can help with anything and we'll reopen this issue!
