### ISSUE TITLE
Git-clone fails - ERROR: checkout (master): Fetch failed, error: exit status 128

### ISSUE THREAD

**Issue by bkmalkoc** [bitrise-io/steps-git-clone#82]
id: git-clone                                                                |
| version: 4.0.11                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2018-05-25T16:44:44Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[16:44:44] Start installing (golang) with apt-get       
INFO[16:44:44]  * [OK] Step dependency (go) installed, available. 
config:
- RepositoryURL: ssh://url@url.url.com:22/me/_git/android
- CloneIntoDir: /bitrise/src
- Commit: 
- Tag: 
- Branch: master
- BranchDest: 
- PRID: 0
- PRRepositoryURL: 
- PRMergeBranch: 
- ResetRepository: false
- CloneDepth: 0
- BuildURL: https://www.bitrise.io/build/....
- BuildAPIToken: 2M5MsPj26Igl80bmER3fgw
- UpdateSubmodules: true
- ManualMerge: true
git "init"
Initialized empty Git repository in /bitrise/src/.git/
git "remote" "add" "origin" "ssh://url@url.url.com:22/me/_git/android"
git "fetch" "origin" "master"
Attempt 1 failed:
exit status 128
Retrying...
git "fetch" "origin" "master"
ssh: connect to host url.url.com port 22: Connection timed out
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Attempt 2 failed:
exit status 128
Retrying...
git "fetch" "origin" "master"
ssh: connect to host url.url.com port 22: Connection timed out
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
ssh: connect to host url.url.com port 22: Connection timed out
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Attempt 3 failed:
exit status 128
ERROR: checkout (master): Fetch failed, error: exit status 128

It was working just 2 days ago within the same version but not working right now. What's the issue?

**Comment by BirmacherAkos** [comment]
Hi @bkmalkoc  
We are happy the issue is resolved.

Happy building!
