### ISSUE TITLE
Allow fetching specific refs

### ISSUE THREAD

**Issue by LukasKnuthImagineOn** [bitrise-io/steps-git-clone#83]
I'm implementing automatic building of Pull-Requests from a self-hosted GitLab instance.

When a PR is created in GitLab, it creates a new Ref on the Server, which points to the merged commit. This ref is of the form `refs/merge-requests/<id>/head`. To checkout the commit, two steps are required:

```bash
# Fetch the ref and map it to a local branch
git fetch origin merge-requests/<id>/head:<local-name>
# Checkout 
git checkout <local-name>
```

The `<local-name>` can be anything (as long as it's a valid ref). After checking out the branch, we can continue building it.

Alternatively, additional refs can be specified in the git config which will cause them to be fetched with a normal `git fetch`-command. See the [GitLab Documentation](https://docs.gitlab.com/ee/user/project/merge_requests/#checkout-merge-requests-locally) for more info. This can also be specified for the initial Clone, when using [the `-c` Flag](https://git-scm.com/docs/git-clone#git-clone--cltkeygtltvaluegt).

**Currently**, I have the normal Git checkout step and after that a short Script step, that runs the two above steps. I wish this was easier and could be specified in the Clone step itself.

On a related note, something similar is [available for GitHub](https://help.github.com/articles/checking-out-pull-requests-locally/), which could eliminate the REST API call in the current step.

**Comment by trapacska** [comment]
Hey @LukasKnuthImagineOn!

Thank you! I've scheduled to look into this. We'll get back to you. 🚀

**Comment by viktorbenei** [comment]
Hi @LukasKnuthImagineOn ,

May I ask what's the issue with the current version of the step?

> The build is triggered by another system (which sees the changes).

See https://devcenter.bitrise.io/api/build-trigger/#pull-request-specific

If you specify all of these then the Git Clone step will detect that it's a PR build and:

1. Clone the Target/Destination branch
1. Then merge the source onto it

It'll do it manually as that's a git service provider *independent* solution.

We do have something similar to what you described for GitHub as an option in this step, but that's turned off by default and not recommended.

Is there a reason why you'd need the ` merge-requests/<id>/head:<local-name>` branch? That's the same as the source of the PR, it's not a pre-merge state as far as I know.

A PR build is supposed to test the **merged** state of the code, the one you'd get after you merge that PR into its target.

**Comment by bitrise-adam** [comment]
No response so I'm closing this.
