### ISSUE TITLE
Step should show the commit hash at the head of the branch being built

### ISSUE THREAD

**Issue by pzearfoss** [bitrise-io/steps-git-clone#9]
This could help in clarifying when something goes wrong.  We should add a log message to the effect of:
'Branch QA set up to track remote branch QA from origin with hash: xxxx'

**Comment by viktorbenei** [comment]
You should see the commit hash (if it was provided) at the top of the step's log. Before it would do anything it prints a summary of it's configurations: https://github.com/bitrise-io/steps-git-clone/blob/master/git_clone.rb#L64

Did it fail before this configuration print?

**Comment by godrei** [comment]
@pzearfoss Checkouted commit hash is printed at the end of the steps's log.
It equals with the output of call (`git log -1 --format="%H"`) in the cloned repository.
